name: 🤖 Themis Code Review
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: ils15/infra-ofertachina/actions/themis-review@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          themis_api_key: ${{ secrets.THEMIS_API_KEY }}
